services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    labels: []
    restart: "no"

  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./data/uploads:/app/data/uploads
      - ./data/images:/app/data/images
    restart: "no"
